### ISSUE TITLE
Where is the code and the notebooks from which the results were acquired ?

### ISSUE THREAD

**Issue by deadskull7** [JunMa11/COVID-19-CT-Seg-Benchmark#1]

**Comment by JunMa11** [comment]
Dear @deadskull7 ,

I'm sorry for the confusion.

All the baseline results are based on [nnU-Net](https://github.com/MIC-DKFZ/nnUNet) which is an out-of-the-box tool. It has provided detailed information about how to use the code.

After installing the nnunet, just download the [trained models](https://zenodo.org/record/3789644#.Xrtgn6gzZPY) and put them into the model folder,  you can reproduce our results by running the inference code.

Best regards,
Jun
