### ISSUE TITLE
Feasibility of Few shot segmentation (specifically task 3)

### ISSUE THREAD

**Issue by Tianyangg** [JunMa11/COVID-19-CT-Seg-Benchmark#2]
Hi JunMa,

Maybe this is not the correct thread for asking but I'm working on this segmentation benchmark and my supervisor plan to extend this for the individual project. Do you think this task of few-shot learning (maybe a transfer from NSCLC or similar dataset) is feasible because as far as know (correct me if I'm wrong) few-shot learning in segmentation in the medical domain is still not well explored? 
Or if you have any suggesting method in mind that I can start with?

Thanks

**Comment by JunMa11** [comment]
Hi @Tianyangg ,

Great question!

>  Do you think this task of few-shot learning (maybe a transfer from NSCLC or similar dataset) is feasible?

For lung segmentation, we have obtained promising results. However, for infection, it still remains a challenging open question.

What we have done is only a very basic baseline, there are several methods that could try, e.g., fine-tune, self-supervised learning, and so on.

Best,
Jun

**Comment by Tianyangg** [comment]
Hi,

Thanks for your advice, we'll take a look at methods like transfer learning stuff.
We really appreciate your work. Thank you.

Regards,
Tian
