### ISSUE TITLE
About the patients of COVID-19-CT-Seg

### ISSUE THREAD

**Issue by ankangd** [JunMa11/COVID-19-CT-Seg-Benchmark#3]
What number of patients do these 20 CT volumes of 'COVID-19-CT-Seg' contain?  Did they come from 20 individual patients?

**Comment by JunMa11** [comment]
19.

`radiopaedia_10_85902_1` and `radiopaedia_10_85902_3` are from the same patient.

**Comment by ankangd** [comment]
Thank you!
