### ISSUE TITLE
Can nnUNet be used as a crop preprocessing in semi-supervised segmentation?

### ISSUE THREAD

**Issue by yasuobinggan** [JunMa11/COVID-19-CT-Seg-Benchmark#4]
Hi JunMa, crop preprocessing based on labels is very common in medical image segmentation task. In Task 1, I want to continue to improve the effect through semi-supervised learning, but the unsupervised data requires crop preprocessing. Can I provide a pseudo-label for data preprocessing based on rough segmentation of unsupervised data based on baseline model in each fold? I wonder that if this process will be considered to be cheating?  Thank you very much!

**Comment by JunMa11** [comment]
Hi @yasuobinggan ,

> Can I provide a pseudo-label for data preprocessing based on rough segmentation of unsupervised data based on baseline model in each fold?

Sorry, I do not understand this.

Could you restatement your question?

**Comment by yasuobinggan** [comment]
Sorry, my English is a little poor.
I mean in the semi-supervised segmentation, I also want to pre-crop the unsupervised data according to the rough segmentation, which is the label inferred from the baseline method on the unsupervised data.
半监督设置中，我想在数据预处理阶段对无监督数据也进行基于标签的预crop (根据标签把roi的大致区域切下来), 我想用baseline的nnUNet来提供这个标签。这样处理中一是对无监督数据进行切分预处理，是否违反无监督设置；二是最后还是会在无监督数据上测试衡量效果(transdudtive设置)，不清楚以上两点是否违规。

**Comment by JunMa11** [comment]
Hi @yasuobinggan ,

我们的benchmark没有设置benchmark的task，所以不存在违规/不违规的问题。
实验中只需要保证你的对比公平即可，比如你自己设计的半监督方法用了crop，那么baseline的方法也应该建立在 crop基础上。

**Comment by yasuobinggan** [comment]
好的，非常感谢您的回复！也感谢你们提供的benchmark！
