### ISSUE TITLE
关于一个新冠分割数据的问题

### ISSUE THREAD

**Issue by yasuobinggan** [JunMa11/COVID-19-CT-Seg-Benchmark#5]
您好，在task1中，我们关注到radiopaedia_29_86490_1这个数据的感染标注非常少，不同于其他数据。在对左右肺感染联合分割时，对这个数据的感染的分割非常困难，在验证集上其他数据得到的感染评价结果与该数据之间存在巨大的差异，请问radiopaedia_29_86490_1的病灶分割是否存在一个比较量化的评价标准以供我们分析这个问题出现的原因？

**Comment by JunMa11** [comment]
这是分割中很常见的情形，不同的病例分割难易度会不一样，因此我们设置了5-fold 交叉验证，这个病例也会不出现在测试集中。
通过violin/boxplot图能展示出这个分割精度低的病例。

**Comment by yasuobinggan** [comment]
非常抱歉回复晚，我们看到在task1的5折交叉验证中，上面提到的这个困难数据有4次出现在验证(测试)集中，想请问您所提到的测试数据是否是指单独进行测试的mosmed数据集，而不是在交叉验证过程中使用的验证(测试)数据？

**Comment by JunMa11** [comment]
是的，这个hard case会出现4次在测试集中。上面说的就是这个。
这是分割中很常见的情形，也是正常情形。
你为了指标好看，可以把这个病例剔除掉算，文中辅以显示的说明。

**Comment by yasuobinggan** [comment]
好的，感谢您的回复。
