### ISSUE TITLE
The MosMed dataset problem.

### ISSUE THREAD

**Issue by ArthurRyan0803** [JunMa11/COVID-19-CT-Seg-Benchmark#6]
I have downloaded the MosMed dataset from the official website https://mosmed.ai/datasets/covid19_1110, but I could only find infection label files in the downloaded data. How to use it for the testing purpose in the lung segmentation subtask of Task1?

**Comment by JunMa11** [comment]
Hi @ArthurRyan0803 ,

The lung mask of the MosMed dataset is not available.
We only report the infection segmentation performance on the MosMed dataset:)

Best,
Jun
