### ISSUE TITLE
Request to use your COVID-19-CT-Seg segmentation dataset in our challenge

### ISSUE THREAD

**Issue by faresbougourzi** [JunMa11/COVID-19-CT-Seg-Benchmark#7]
Hi, thank you for providing such a wonderful Dataset

We are working to release a challenge on Covid-19, and we are wondering if we can use your COVID-19-CT-Seg segmentation dataset in our challenge 

Best Regards

**Comment by JunMa11** [comment]
@faresbougourzi , thanks for your interest very much.

Sure. 
Please also give the credits to the other contributors as listed in 
https://github.com/JunMa11/COVID-19-CT-Seg-Benchmark#acknowledgements

**Comment by faresbougourzi** [comment]
Sure, Thanks a lot 

Best regards
