### ISSUE TITLE
Can't find data

### ISSUE THREAD

**Issue by pvkiennn** [JunMa11/COVID-19-CT-Seg-Benchmark#8]
Thanks for sharing a wonderful project.
I have a problem with data permission because the link can't permit me to download. Can you give the way download dataset StructSeg 2019?

Best regards!

**Comment by JunMa11** [comment]
Hi @pvkiennn ,

Thanks for your interest.
We are not allowed to share the StructSeg dataset. Please reach out to the corresponding organizers to obtain the data.
